import { useEffect, useState } from 'react';
import { matchService } from '../../services/match.service';
import type { Match } from '../../services/match.service';
import { formatCurrency } from '../../utils/formatters';
import { Card } from '../../components/ui/Card';
import { Badge } from '../../components/ui/Badge';
import { StatusBadge } from '../../components/ui/StatusBadge';
import { Button } from '../../components/ui/Button';
import { LoadingState } from '../../components/ui/LoadingState';
import { Icon } from '../../components/ui/Icon';
import '../dashboard.css';

export default function LawyerMatchesPage() {
  const [matches, setMatches] = useState<Match[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [updatingId, setUpdatingId] = useState<string | null>(null);

  useEffect(() => {
    matchService
      .getMatchesForLawyer()
      .then((data) => setMatches(data || []))
      .catch((err) => console.error(err))
      .finally(() => setIsLoading(false));
  }, []);

  const handleUpdateStatus = async (matchId: string, status: 'ACCEPTED' | 'DECLINED') => {
    setUpdatingId(matchId);
    try {
      await matchService.updateMatchStatus(matchId, status);
      setMatches((prev) =>
        prev.map((m) => (m.id === matchId ? { ...m, status } : m))
      );
    } catch {
      alert('Failed to update match status');
    } finally {
      setUpdatingId(null);
    }
  };

  if (isLoading) return <LoadingState message="Loading client matches..." />;

  return (
    <div className="dashboard-container">
      <div className="dashboard-header">
        <div className="dashboard-header-title">
          <h1>My Client Matches</h1>
          <p>Review startup legal request matches generated by Counselly’s automated match engine</p>
        </div>
      </div>

      {matches.length === 0 ? (
        <Card style={{ textAlign: 'center', padding: 'var(--space-8)' }}>
          <h3>No Matches Yet</h3>
          <p style={{ color: 'var(--color-slate-600)', margin: 'var(--space-2) 0' }}>
            As startups create requests matching your legal experience and jurisdiction, matches will appear here automatically.
          </p>
        </Card>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-5)' }}>
          {matches.map((match) => (
            <Card key={match.id} style={{ display: 'flex', flexDirection: 'column', gap: 'var(--space-4)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 'var(--space-4)' }}>
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-3)', marginBottom: 'var(--space-2)' }}>
                    <h3 style={{ fontSize: 'var(--text-xl)', fontWeight: 700, color: 'var(--color-navy)' }}>
                      {match.legalRequest?.title || 'Legal Request'}
                    </h3>
                    <span className="match-score-badge">
                      <Icon name="sparkles" /> High Compatibility Match
                    </span>
                    <StatusBadge status={match.status} type="match" />
                  </div>
                  <p style={{ fontSize: 'var(--text-sm)', color: 'var(--color-slate-600)' }}>
                    Client: <strong>{match.startup?.companyName || 'Startup Company'}</strong> • Industry: {match.legalRequest?.industry || 'General'} • Jurisdiction: {match.legalRequest?.jurisdiction || 'All'}
                  </p>
                </div>

                <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-3)' }}>
                  {match.status === 'PENDING' && (
                    <>
                      <Button
                        variant="secondary"
                        size="sm"
                        isLoading={updatingId === match.id}
                        onClick={() => handleUpdateStatus(match.id, 'DECLINED')}
                      >
                        Decline
                      </Button>
                      <Button
                        variant="primary"
                        size="sm"
                        isLoading={updatingId === match.id}
                        onClick={() => handleUpdateStatus(match.id, 'ACCEPTED')}
                      >
                        Accept Match
                      </Button>
                    </>
                  )}
                  {match.status === 'ACCEPTED' && (
                    <span style={{ fontSize: 'var(--text-sm)', color: '#059669', fontWeight: 600 }}>
                      ✓ Match Accepted — Startup will initiate contact
                    </span>
                  )}
                  {match.status === 'ENGAGED' && (
                    <span style={{ fontSize: 'var(--text-sm)', color: 'var(--color-gold)', fontWeight: 700 }}>
                      ★ Active Engagement
                    </span>
                  )}
                </div>
              </div>

              <div style={{ background: 'var(--color-ivory)', padding: 'var(--space-4)', borderRadius: 'var(--radius-md)', border: '1px solid var(--color-border)' }}>
                <h4 style={{ fontSize: 'var(--text-xs)', color: 'var(--color-slate-500)', textTransform: 'uppercase', marginBottom: '8px' }}>
                  MATCH REASONS & FIT ANALYSIS
                </h4>
                <div className="tag-cloud">
                  {match.matchReasons.map((reason, idx) => (
                    <Badge key={idx} variant="gold">
                      ✓ {reason}
                    </Badge>
                  ))}
                </div>
              </div>

              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', fontSize: 'var(--text-sm)', color: 'var(--color-slate-600)' }}>
                <div>
                  Expected Hours: <strong>{match.legalRequest?.expectedHours || 0} hrs/mo</strong>
                </div>
                <div>
                  Budget Range: <strong>{formatCurrency(match.legalRequest?.budgetMin, match.legalRequest?.currency)} - {formatCurrency(match.legalRequest?.budgetMax, match.legalRequest?.currency)}/mo</strong>
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
